### PR TITLE
Expose parameter red days, add latest handbook link to readme, increase reliability of setup.R

### PR DESCRIPTION
**Pull request by ashlinrichardson**
Hi All,
For your review a couple minor change:
- within "simulation.js" exposed "red days" parameter within run.R (Ernie pls. verify if I got the parameter name correctly) 
- added link in README.md to latest version of handbook (pls verify it's the correct one)
- added a try/catch statement in the setup.R that reattempts library install with an explicit URL (if not using one fails)
cheers

### CODE REVIEW

**Comment by ecsendmail** [comment]
On Sun, Feb 28, 2021 at 9:50 PM Ashlin Richardson <notifications@github.com>
wrote:

> Hi All,
> For your review a couple minor change:
>
>    - within "simulation.js" exposed "red days" parameter within run.R
>    (Ernie pls. verify if I got the parameter name correctly)
>
>
*THE ACTUAL NAME OF THE PARAMETER IS "SYMPTOMATIC CASES" AND THE NUMBER
13.2 REFERS TO THE END OF ITS LIFE-TIME......*
*THE NUMBER ASSOCIATED WITH YELLOW ("INCUBATING") IS 2.2 BECAUSE ITS
DURATION IS FROM 0 TO 2.2*
*THE NUMBER ASSOCIATED WITH BLUE ("PRESYMPTOMATIC" IS 5.2 BECAUSE ITS
DURATION IS FROM 2.2 TO 5.2 - DAYS*
*THE NUMBER ASSOCIATED WITH RED ("SYMPTOMATIC CASES" IS 13.2 BECAUSE ITS
DURATION IS FROM 5.2 TO 13.2 - 8 DAYS*

*WE COULD HAVE THEM AS 2.2, 3 AND 8 BUT THE 2.2, 5.2 AND 13.2 IS
LONGITUDINAL *

>
>    - added link in README.md to latest version of handbook (pls verify
>    it's the correct one)
>
> *THE HANDBOOK IS HOPELESSLY OUT OF DATE, AND IS A ROUGH GUIDE TO THE
STRUCTURE OF THE PROGRAM.....I THINK YOU ARE BOTH CODE READERS AND DO NOT
NEED IT*

**Comment by ashlinrichardson** [comment]
Roger that thanks @ecsendmail ! I love the LONGDITUDINAL mindset. Just wanted to confirm, is the identification below good, before I merge in the change?
```
   try {
      VLinfEnd = SYMPTOMATIC_CASES; // does VLinfEnd_R exist?
    } catch {
    }

    try {
      VLonsetT = PRESYMPTOMATIC;
    } catch {
    }

    try {
      VLincD = INCUBATING;
    } catch {
    }
```

**Comment by ecsendmail** [comment]
Yes, that's it.

**Comment by ashlinrichardson** [comment]
Thanks @ecsendmail will merge then. cheers

**Pull request merged**
