### PR TITLE
expose HAZARD RADIUS and MINGLE FACTOR

### PR DESCRIPTION
**Pull request by ashlinrichardson**

### CODE REVIEW

**Comment by ashlinrichardson** [comment]
HI @ecsendmail just to be careful..

..is this how MINGLE_FACTOR should be set?

https://github.com/ecsendmail/MultiverseContagion/pull/13/files

**Comment by ashlinrichardson** [comment]
I'll assume it's good for now. @ecsendmail  definitely let me know if I messed it up and can fix later! thanks

**Comment by ecsendmail** [comment]
HI Ash:

I see all the commits and merges but I don't know how to visualize the
results....I hope you will spend an hour showing us what you did and run
them....I don't see any screen shots nor where things change except that
you have merged changes into Master....

Apologies but not apparent...

Ernie

**Comment by ashlinrichardson** [comment]
OK @ecsendmail will add tests later to show that changing these parameters change the results..
.. but first, running many simulations in parallel (looks like it takes 20s to run 100 simulations on my computer)
Back soon..

**Comment by ashlinrichardson** [comment]
Will do

**Pull request merged**
